### PR TITLE
docs: Clarify PAT for Orgs

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
Wait, no; I think I've misunderstood how this works... I'll update this PR.

**Comment by vorburger** [comment]
Voilà, apparently that's is how PATs work for GitHub Orgs...

**Comment by EndBug** [comment]
Awesome! Thanks for the PR 🙏🏻 
I'll get to all of them one by one ahahhah

**Comment by EndBug** [comment]
@all-contributors please add @vorburger for their docs contribution

**Comment by EndBug** [comment]
@all-contributors please add @vorburger for their docs contribution

**Pull request merged**
